/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.MedicamentoDAO;
import Model.MedicamentoTableModel;
import Objetos.Funcionario;
import Objetos.Medicamento;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author luis.fmleite
 */

public class CadastroMedicamento extends javax.swing.JFrame {
    private Funcionario user;
    private Menu menu;

    MedicamentoTableModel modelo = new MedicamentoTableModel();

    /**
     * Creates new form CadastroMedicamento
     */
    public CadastroMedicamento() {
        initComponents();
    }

    public CadastroMedicamento(Funcionario user, Menu menu) {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.user = user;
        this.menu = menu;
        this.setLocationRelativeTo(null);
        jTTabelaMed.setModel(modelo);
        modelo.recarregaTabela();
        styleComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTDescricaoMedicamento = new javax.swing.JTextField();
        jBCadastrarMed = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTQuantidadeMedicamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTNomeMedicamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBVoltarCadastroMedicamento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabelaMed = new javax.swing.JTable();
        jBExcluirMed = new javax.swing.JButton();
        jBAlterarMed = new javax.swing.JButton();
        jTCodigoCatalogo = new javax.swing.JTextField();
        jTDataValidadeMedicamento = new javax.swing.JFormattedTextField();
        jTValorMedicamento = new javax.swing.JFormattedTextField();
        jBDesativados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel2.setText("Nome:");

        jLabel8.setText("Descrição:");

        jLabel3.setText("Código Catálogo:");

        jTDescricaoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDescricaoMedicamentoActionPerformed(evt);
            }
        });

        jBCadastrarMed.setText("Cadastrar");
        jBCadastrarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarMedActionPerformed(evt);
            }
        });

        jLabel5.setText("Data Validade:");

        jLabel6.setText("Número:");

        jLabel7.setText("Valor:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO MEDICAMENTO");

        jBVoltarCadastroMedicamento.setText("Voltar");
        jBVoltarCadastroMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarCadastroMedicamentoActionPerformed(evt);
            }
        });

        jTTabelaMed.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jTTabelaMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaMedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTabelaMed);

        jBExcluirMed.setText("Excluir");
        jBExcluirMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirMedActionPerformed(evt);
            }
        });

        jBAlterarMed.setText("Alterar");
        jBAlterarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarMedActionPerformed(evt);
            }
        });

        // Máscara removida para evitar conflito de digitação
        jTCodigoCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodigoCatalogoActionPerformed(evt);
            }
        });

        try {
            jTDataValidadeMedicamento.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        // Removida a máscara de telefone para o valor, pois causava erro de conversão
        jTValorMedicamento.setFormatterFactory(null);

        jBDesativados.setText("Desativados");
        jBDesativados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDesativadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jBDesativados)
                                                .addGap(18, 18, 18)
                                                .addComponent(jBAlterarMed)
                                                .addGap(18, 18, 18)
                                                .addComponent(jBExcluirMed)
                                                .addGap(18, 18, 18)
                                                .addComponent(jBCadastrarMed)
                                                .addGap(18, 18, 18)
                                                .addComponent(jBVoltarCadastroMedicamento))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jTCodigoCatalogo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jTQuantidadeMedicamento,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jLabel5)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jTDataValidadeMedicamento,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jLabel7)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jTValorMedicamento,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jTNomeMedicamento,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 450,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jLabel8)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jTDescricaoMedicamento)))))
                                .addGap(40, 40, 40)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jTNomeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(jTDescricaoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jTCodigoCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jTQuantidadeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTDataValidadeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(jTValorMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBCadastrarMed)
                                        .addComponent(jBVoltarCadastroMedicamento)
                                        .addComponent(jBExcluirMed)
                                        .addComponent(jBAlterarMed)
                                        .addComponent(jBDesativados))
                                .addGap(30, 30, 30)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDescricaoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDescricaoMedicamentoActionPerformed

    }//GEN-LAST:event_jTDescricaoMedicamentoActionPerformed

    private void jBCadastrarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarMedActionPerformed
        try {
            if (jTNomeMedicamento.getText().trim().isEmpty() || jTCodigoCatalogo.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Por favor, preencha o Nome e o Código do Catálogo.");
                return;
            }
            Medicamento cmed = new Medicamento();
            MedicamentoDAO dao = new MedicamentoDAO();
            cmed.setNomeMed(jTNomeMedicamento.getText());
            cmed.setDescricaoMed(jTDescricaoMedicamento.getText());
            cmed.setQuantidadeMed(Integer.parseInt(jTQuantidadeMedicamento.getText().trim()));
            String valorStr = jTValorMedicamento.getText().replace("R$", "").replace(" ", "").replace(",", ".").trim();
            cmed.setValorMed(Double.valueOf(valorStr));
            cmed.setDataValidadeMed(jTDataValidadeMedicamento.getText().replace("/", "-"));
            cmed.setCodCatMed(Integer.parseInt(jTCodigoCatalogo.getText().trim()));
            dao.create(cmed);
            modelo.recarregaTabela();
            LimpaCampos();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Erro nos campos numéricos: Verifique se Quantidade, Valor e Código são apenas números.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + e.getMessage());
        }

    }//GEN-LAST:event_jBCadastrarMedActionPerformed

    private void jTNomeMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeMedicamentoActionPerformed

    }//GEN-LAST:event_jTNomeMedicamentoActionPerformed

    private void jBVoltarCadastroMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarCadastroMedicamentoActionPerformed
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBVoltarCadastroMedicamentoActionPerformed

    private void jBExcluirMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirMedActionPerformed
        if (jTTabelaMed.getSelectedRow() != -1) {
            Medicamento cmed = modelo.pegaDadosLinha(jTTabelaMed.getSelectedRow());
            MedicamentoDAO dao = new MedicamentoDAO();
            dao.delete(cmed);
            modelo.recarregaTabela();
        }
    }//GEN-LAST:event_jBExcluirMedActionPerformed

    private void jBAlterarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarMedActionPerformed
        if (jTTabelaMed.getSelectedRow() != -1) {
            Medicamento cmed = modelo.pegaDadosLinha(jTTabelaMed.getSelectedRow());
            cmed.setNomeMed(jTNomeMedicamento.getText());
            cmed.setDescricaoMed(jTDescricaoMedicamento.getText());
            cmed.setQuantidadeMed(Integer.parseInt(jTQuantidadeMedicamento.getText().trim()));
            cmed.setValorMed(Double.valueOf(jTValorMedicamento.getText().replace(",", ".").trim()));
            cmed.setDataValidadeMed(jTDataValidadeMedicamento.getText().replace("/", "-"));
            cmed.setCodCatMed(Integer.parseInt(jTCodigoCatalogo.getText().trim()));

            MedicamentoDAO dao = new MedicamentoDAO();
            dao.update(cmed);
            LimpaCampos();
            modelo.recarregaTabela();
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Selecione um medicamento para alterar.");
        }
    }//GEN-LAST:event_jBAlterarMedActionPerformed

    private void jTTabelaMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaMedMouseClicked
        if (jTTabelaMed.getSelectedRow() != -1) {
            Medicamento cmed = modelo.pegaDadosLinha(jTTabelaMed.getSelectedRow());
            jTNomeMedicamento.setText(cmed.getNomeMed());
            jTDescricaoMedicamento.setText(cmed.getDescricaoMed());
            
            String dataVal = cmed.getDataValidadeMed();
            if (dataVal != null) {
                jTDataValidadeMedicamento.setText(dataVal.replace("-", "/"));
            } else {
                jTDataValidadeMedicamento.setText("");
            }
            
            jTValorMedicamento.setText(String.valueOf(cmed.getValorMed()));
            jTQuantidadeMedicamento.setText(String.valueOf(cmed.getQuantidadeMed()));
            jTCodigoCatalogo.setText(String.valueOf(cmed.getCodCatMed()));
        }
    }//GEN-LAST:event_jTTabelaMedMouseClicked

    private void jTValorMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTValorMedicamentoActionPerformed

    }//GEN-LAST:event_jTValorMedicamentoActionPerformed

    private void jTDataValidadeMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDataValidadeMedicamentoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTDataValidadeMedicamentoActionPerformed

    private void styleComponents() {
        getContentPane().setBackground(new Color(30, 30, 30));

        // Labels
        javax.swing.JLabel[] labels = { jLabel1, jLabel2, jLabel3, jLabel5, jLabel6, jLabel7, jLabel8 };
        for (javax.swing.JLabel lbl : labels) {
            lbl.setForeground(Color.WHITE);
        }
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));

        // TextFields
        javax.swing.JTextField[] fields = { jTNomeMedicamento, jTDescricaoMedicamento, jTCodigoCatalogo,
                jTQuantidadeMedicamento, jTDataValidadeMedicamento, jTValorMedicamento };
        for (javax.swing.JTextField fld : fields) {
            fld.setBackground(new Color(60, 60, 60));
            fld.setForeground(Color.WHITE);
            fld.setCaretColor(Color.WHITE);
            fld.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(80, 80, 80)));
        }

        // Buttons
        javax.swing.JButton[] botoes = { jBCadastrarMed, jBAlterarMed, jBExcluirMed, jBDesativados,
                jBVoltarCadastroMedicamento };
                for (javax.swing.JButton btn : botoes) {
            btn.setBackground(new java.awt.Color(45, 45, 45));
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
            btn.setPreferredSize(new java.awt.Dimension(160, 40));
            btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 70, 70)));
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }
        jBCadastrarMed.setBackground(new Color(0, 100, 0));
        jBAlterarMed.setBackground(new Color(0, 120, 215));
        jBExcluirMed.setBackground(new Color(150, 0, 0));
        jBDesativados.setBackground(new Color(100, 100, 0));

        // Table
        jTTabelaMed.setBackground(new Color(60, 60, 60));
        jTTabelaMed.setForeground(Color.WHITE);
        jTTabelaMed.setGridColor(new Color(80, 80, 80));
        jTTabelaMed.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        jTTabelaMed.setRowHeight(25);
        jTTabelaMed.setSelectionBackground(new Color(0, 100, 0, 80));
        jTTabelaMed.setSelectionForeground(Color.WHITE);
        jTTabelaMed.getTableHeader().setBackground(new Color(30, 30, 30));
        jTTabelaMed.getTableHeader().setForeground(Color.WHITE);
        jTTabelaMed.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        jTTabelaMed.setFillsViewportHeight(true);
        jScrollPane1.getViewport().setBackground(new Color(45, 45, 45));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }

    private void LimpaCampos() {
        jTCodigoCatalogo.setText("");
        jTDataValidadeMedicamento.setText("");
        jTDescricaoMedicamento.setText("");
        jTNomeMedicamento.setText("");
        jTQuantidadeMedicamento.setText("");
        jTValorMedicamento.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMedicamento().setVisible(true);
            }
        });
    }

    private void jBDesativadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDesativadosActionPerformed
        Med_Inativos m = new Med_Inativos(modelo);
        m.setVisible(true);
    }//GEN-LAST:event_jBDesativadosActionPerformed

    private void jTCodigoCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodigoCatalogoActionPerformed
    }//GEN-LAST:event_jTCodigoCatalogoActionPerformed

    private void jTQuantidadeMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTQuantidadeMedicamentoActionPerformed
    }//GEN-LAST:event_jTQuantidadeMedicamentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterarMed;
    private javax.swing.JButton jBCadastrarMed;
    private javax.swing.JButton jBDesativados;
    private javax.swing.JButton jBExcluirMed;
    private javax.swing.JButton jBVoltarCadastroMedicamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodigoCatalogo;
    private javax.swing.JFormattedTextField jTDataValidadeMedicamento;
    private javax.swing.JTextField jTDescricaoMedicamento;
    private javax.swing.JTextField jTNomeMedicamento;
    private javax.swing.JTextField jTQuantidadeMedicamento;
    private javax.swing.JTable jTTabelaMed;
    private javax.swing.JFormattedTextField jTValorMedicamento;
    // End of variables declaration//GEN-END:variables
}
